// ADMIN REDUCEER TYPES

export const ADMIN_SIGNIN_REQUEST = "ADMIN_SIGNIN_REQUEST";
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS";
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL";

export const ADMIN_SIGNUP_REQUEST = "ADMIN_SIGNUP_REQUEST";
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS";
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL";

export const ADMIN_UPDATE_REQUEST = "ADMIN_SIGNUP_REQUEST";
export const ADMIN_UPDATE_SUCCESS = "ADMIN_UPDATE_SUCCESS";
export const ADMIN_UPDATE_FAIL = "ADMIN_UPDATE_FAIL";


//ADMIN USER ACTIONS
export const ADMIN_BLOCK_USER = "ADMIN_BLOCK_USER";
export const ADMIN_BLOCK_USER_SUCCESS = "ADMIN_BLOCK_USER_SUCCESS";
export const ADMIN_BLOCK_USER_FAILED = "ADMIN_BLOCK_USER_FAILED";

export const ADMIN_UNBLOCK_USER = "ADMIN_UNBLOCK_USER";
export const ADMIN_UNBLOCK_USER_SUCCESS = "ADMIN_UNBLOCK_USER_SUCCESS";
export const ADMIN_UNBLOCK_USER_FAILED = "ADMIN_UNBLOCK_USER_FAILED";

export const ADMIN_DELETE_USER = "ADMIN_DELETE_USER";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_FAILED = "ADMIN_DELETE_USER_FAILED";